import Tracker from "@/components/tracker";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn("scroll-smooth", inter.className)}>
      <body
        suppressHydrationWarning={true}
        className="bg-stone-100 text-stone-700 dark:bg-slate-900 dark:text-slate-400 leading-relaxed antialiased 
        selection:bg-pink-300
        dark:selection:bg-teal-300 dark:selection:text-teal-900
        ">
        <Tracker />
        <div className="mx-auto min-h-screen max-w-screen-xl px-6 py-12 font-sans md:px-12 md:py-20 lg:px-24 lg:py-0">{children}</div>
      </body>
    </html>
  );
}
